apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: compx576-frontend
  namespace: compx576
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - smart-farm.app
        - "*.smart-farm.app"
      secretName: compx576-tls
  rules:
    - host: smart-farm.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
    - host: www.smart-farm.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: compx576-api
  namespace: compx576
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - smart-farm.app
        - "*.smart-farm.app"
      secretName: compx576-tls
  rules:
    - host: smart-farm.app
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: web-server
                port:
                  number: 8080
    - host: www.smart-farm.app
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: web-server
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: compx576-agent-api
  namespace: compx576
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - smart-farm.app
        - "*.smart-farm.app"
      secretName: compx576-tls
  rules:
    - host: smart-farm.app
      http:
        paths:
          - path: /agent(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: agent-server
                port:
                  number: 8081
    - host: www.smart-farm.app
      http:
        paths:
          - path: /agent(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: agent-server
                port:
                  number: 8081
